### ISSUE TITLE
カードブロック

### ISSUE THREAD

**Issue by fumikito** [kuno1/block-library#7]
- 画像
- テキスト
- リンク

「おすすめガジェット」みたいな感じでリンクできる。

**Comment by fumikito** [comment]
@kzoou これのサンプルURLって貼ってもらえますか？

**Comment by kzoou** [comment]
@fumikito 
> @kzoou これのサンプルURLって貼ってもらえますか？

https://makuring.com/
マクリンさんのトップページの最上部の新着記事以外が全て、カードブロック的な感じですね。
投稿リストを表示しつつ、タイトルは後付けで自分で自由に設定できる感じでしょうか。

**Comment by fumikito** [comment]
![スクリーンショット 2020-01-23 14 20 06](https://user-images.githubusercontent.com/84587/72958845-c92d0080-3deb-11ea-9a2c-77b958564074.png)

これは既存のメディアをカスタマイズすればできそうな気がしますね。

**Comment by kzoou** [comment]
どこまでやるかですがSwellではもう少し高度な設定ができるようになってます。
https://swell-theme.com/function/1442/

僕もこのような感じで使ってます。

![FireShot Capture 040 - misclog（ミスクログ） - ガジェットレビューブログ - misc-log com](https://user-images.githubusercontent.com/536501/72959406-8cfa9f80-3ded-11ea-8220-08cdaba7f960.png)

**Comment by kzoou** [comment]
すごいですね、とても使いやすいと思います。
現時点だとこれ以上はちょっと思いつかないですね。

機能要望ではなく、今後の可能性としてですが、タイトルはともかく画像に関しては専用画像を作ることなく、投稿のアイキャッチをそのまま使うケースが人によっては多いかもしれません。

数百枚ある画像から選ぶのはなかなか手間なので、投稿IDなどを入力するとアイキャッチを自動で取得してくるという実装が喜ばれる可能性はあると思います。
